/**
 * Lista de 250 frases reflexivas de bienvenida sobre bienestar emocional.
 * Extraídas de docs/examples/Frases_de_Bienvenida_Animikro.pdf
 */

export const welcomePhrases: string[] = [
  "“Creo en ti y en tu capacidad para lograrlo”.",
  "La vida es 10% lo que experimentas y 90% cómo respondes a ello.",
  "El microlearning 2.0 no es brevedad, es el respeto absoluto al tiempo del aprendiz.",
  "“Tu trabajo es importante y valorado por todos nosotros”.",
  "Acostarse y levantarse temprano hace a un hombre sabio, rico y saludable.",
  "La empatía y los buenos modales no son formalidades, son protectores del clima colaborativo.",
  "“Cuenten conmigo para apoyarlos en lo que necesiten en este proceso”.",
  "El dolor mental es menos dramático que el físico, pero a menudo más difícil de soportar.",
  "La asertividad es la capacidad de ser firme sin perder la empatía por el interlocutor.",
  "“Comprendo cómo te sientes y estoy aquí para escucharte activamente”.",
  "La mejor y más eficiente farmacia está dentro de tu propio sistema biológico.",
  "El aprendizaje reflexivo es el antídoto contra el olvido de la información memorizada.",
  "“Trabajemos juntos para encontrar una solución innovadora a este reto”.",
  "El estado de tu vida no es más que un reflejo del estado de tu mente.",
  "La tecnología invisible en la educación de 2026 elimina la fricción entre el saber y el hacer.",
  "“Vamos a aprender de nuestros errores y mejorar juntos como equipo”.",
  "Quienes piensan que no tienen tiempo para el ejercicio, tarde o temprano tendrán tiempo para la enfermedad.",
  "La comunicación asertiva elimina los preámbulos innecesarios y respeta la agenda ajena.",
  "“Estoy orgulloso/a de lo que hemos logrado como equipo este trimestre”.",
  "De nuestras vulnerabilidades nacen nuestras fortalezas más profundas.",
  "La conciencia social derivada de las Ciencias Sociales es un pilar de la salud mental colectiva.",
  "“¿Qué piensas tú sobre esto? Quiero escuchar tu opinión honesta”.",
  "Correr o hacer ejercicio puede ser una forma de terapia tan válida como la tradicional.",
  "El liderazgo asertivo evita la ambigüedad, principal fuente de estrés laboral.",
  "“Sé que esto es un desafío, pero sé que podemos superarlo juntos”.",
  "La mente tiene una gran influencia sobre el cuerpo, y muchas enfermedades se originan allí.",
  "El microlearning incrustado permite aprender sin abandonar la herramienta de trabajo.",
  "“Sé que a veces es difícil, pero confío plenamente en tus habilidades únicas”.",
  "La salud física es el fundamento de una actividad intelectual creativa y dinámica.",
  "El pensamiento histórico nos ayuda a valorar la diversidad y reducir prejuicios sociales.",
  "“No hay preguntas tontas, pregúntame absolutamente lo que necesites”.",
  "La depresión se define a menudo como la incapacidad de construir o imaginar un futuro.",
  "La gamificación madura sustituye los rankings por narrativas que dan sentido al esfuerzo.",
  "“Quiero asegurarme de que todos estemos en la misma página hoy”.",
  "La esperanza de vida aumentaría si los vegetales fueran tan deseables como los ultraprocesados.",
  "Las habilidades blandas deben ser el eje central de cualquier plan de estudios moderno.",
  "“¿Cómo puedo ayudarte a ser más efectivo y feliz en tu trabajo?”.",
  "Invertir en la salud propia siempre producirá los beneficios más altos y sostenibles.",
  "El aula invertida traslada el estrés de la instrucción al hogar y el alivio de la práctica al aula.",
  "“Tus esfuerzos no pasan desapercibidos para este liderazgo”.",
  "La salud es la mayor posesión; la alegría es el tesoro más grande que puedes tener.",
  "Preguntar “¿Me expresé bien?” es un acto de humildad y claridad asertiva.",
  "“Estoy aquí para brindarte retroalimentación constructiva para tu crecimiento”.",
  "Te tratarán en la vida de la forma en que enseñas a la gente a tratarte.",
  "El mLearning es la modalidad óptima para tratar temas concretos que no requieren presencialidad.",
  "“Agradezco tu dedicación y compromiso inquebrantable con el equipo”.",
  "En la enfermedad, lo más importante es nunca perder el corazón ni la esperanza.",
  "El estilo agresivo de dirección crea un clima laboral de cortisol y miedo.",
  "“Si necesitas apoyo adicional, por favor no dudes en hacérmelo saber”.",
  "Las actitudes negativas nunca podrán resultar en una vida emocionalmente positiva.",
  "Los asistentes contextuales son la evolución final de la tutoría personalizada.",
  "“Cada uno de nosotros aporta algo valioso y único al éxito del equipo”.",
  "Las emociones inexpresadas nunca mueren; se entierran vivas y salen luego con violencia.",
  "El microaprendizaje segmenta la información para evitar la parálisis por sobrecarga.",
  "“Confío en que vamos a encontrar una solución juntos, pase lo que pase”.",
  "El castigo de toda mente desordenada es su propio desorden interno.",
  "La técnica del puzle enseña que somos responsables no solo de lo propio, sino de lo común.",
  "“Estoy aquí para trabajar en colaboración estrecha contigo”.",
  "La propia estima no puede ser verificada por los demás; tú vales por decisión propia.",
  "La puntualidad es un acto de respeto que previene la ansiedad en el equipo.",
  "“Celebremos nuestros éxitos y aprendamos con humildad de nuestros errores”.",
  "La gente se siente mejor consigo misma cuando es buena en algo que ama.",
  "El Aprendizaje Basado en Problemas fomenta la autonomía y la resiliencia cognitiva.",
  "“Juntos somos más fuertes y podemos lograr objetivos mucho más altos”.",
  "La autoestima es el cimiento que sostiene toda la estructura del bienestar mental.",
  "La IA educativa de 2026 no finge ser humana, es una herramienta transparente y útil.",
  "“Estoy seguro/a de que podemos aprender algo valioso de esta situación difícil”.",
  "El miedo y la ansiedad suelen indicar que estamos creciendo fuera de la zona de confort.",
  "Las Ciencias Sociales promueven la mentalidad democrática necesaria para la paz laboral.",
  "“Hablemos abiertamente y resolvamos cualquier problema en el momento en que surja”.",
  "Dormir es la cadena de oro que une la salud con el funcionamiento óptimo.",
  "El microlearning bajo demanda reduce la incertidumbre en el flujo de trabajo.",
  "“Estoy aquí para apoyarte en el logro de todos tus objetivos personales”.",
  "En una mente desordenada, el sonido de la salud es simplemente imposible de escuchar.",
  "El análisis de medios desarrolla la alfabetización necesaria para no ser víctima de la desinformación.",
  "“¿Qué podemos hacer para mejorar nuestra comunicación interna como equipo?”.",
  "No se puede avanzar si siempre estás mirando hacia el pasado con arrepentimiento.",
  "La asertividad es el puente más corto entre un problema y su resolución.",
  "“Aprecio tus ideas y todas tus sugerencias para mejorar nuestros procesos”.",
  "Caminarás hacia el crecimiento o hacia atrás hacia la seguridad del miedo.",
  "Las intervenciones silenciosas basadas en datos protegen la privacidad y el flujo del alumno.",
  "“Agradezco tu dedicación y tu compromiso constante con el trabajo bien hecho”.",
  "Basura que entra, basura que sale: selecciona cuidadosamente qué consumes mentalmente.",
  "La gamificación invisible integra el desafío en la tarea, eliminando la adicción a puntos.",
  "“Siéntete libre de expresarte abiertamente en este espacio seguro para todos”.",
  "La psiquiatría enseña a la gente a mantenerse en sus pies mientras descansan sus mentes.",
  "El pensamiento crítico es el escudo final contra la manipulación de datos.",
  "“Quiero asegurarme de que todos tengamos la información necesaria para triunfar”.",
  "Debemos estar en modo de crecimiento, no solo en modo de supervivencia.",
  "Los módulos de derechos y obligaciones en la formación básica empoderan al ciudadano.",
  "“Tengo absoluta confianza en que superaremos cualquier obstáculo juntos”.",
  "Lo que hay que cambiar en una persona es, ante todo, la conciencia de sí misma.",
  "El microaprendizaje personalizado se ajusta a tus lagunas de conocimiento de forma automática.",
  "“Quiero asegurarme de que estás cómodo/a con tus responsabilidades actuales”.",
  "La salud es la única moneda que no se puede devaluar si se cuida con rigor.",
  "La investigación basada en la comunidad conecta el saber académico con la mejora del barrio.",
  "“Sé que tienes mucho talento y potencial para crecer dentro de esta empresa”.",
  "Si cambias la forma en que miras las cosas, las cosas que miras terminan cambiando.",
  "La comunicación asertiva es la enemiga natural de los rumores y la toxicidad.",
  "“Trabajemos juntos para lograr nuestros objetivos compartidos”.",
  "Una actitud saludable es el mejor activo que un profesional puede aportar al equipo.",
  "La educación a distancia en 2026 prioriza los criterios de evaluación por competencias.",
  "“Valoramos tus habilidades y tu amplia experiencia dentro de este equipo”.",
  "Estar saludable es simplemente la mejor forma de vivir la vida con plenitud.",
  "El análisis de fuentes primarias es fundamental para una ciudadanía informada y reflexiva.",
  "“Estoy aquí para brindarte retroalimentación constructiva y todo mi apoyo”.",
  "Las enfermedades del alma suelen ser más numerosas que las del cuerpo.",
  "El microlearning digital impacta positivamente en la reducción del ausentismo laboral.",
  "“Celebremos nuestras diferencias y trabajemos en armonía total”.",
  "El que tiene salud tiene esperanza, y quien tiene esperanza lo tiene todo.",
  "La intervención automática del sistema evita que el alumno se sienta expuesto en sus errores.",
  "“Sé que esta es una situación difícil, pero confío en nuestra capacidad colectiva”.",
  "Todo el mundo necesita belleza y pan para fortalecer el cuerpo y el alma.",
  "Las habilidades comunicacionales son el diferencial real ante la automatización masiva.",
  "“Todos tenemos un papel importante que desempeñar en este gran equipo”.",
  "Ser honesto con uno mismo es la primera ley de la salud emocional.",
  "La IA educativa genera casos prácticos distintos cada año para evitar el aprendizaje estático.",
  "“Estoy disponible para discutir cualquier preocupación que tengas en mente”.",
  "No hay estrés en el mundo, solo hay mentes pensando pensamientos estresantes.",
  "El mLearning permite que el aprendizaje ocurra en los intersticios productivos del día.",
  "“Quiero asegurarme de que te sientas valorado/a siempre en este equipo”.",
  "Mientras que el miedo agota el poder, la fe y la esperanza dan alas al alma.",
  "El Aprendizaje Basado en Problemas transforma la teoría en una herramienta de vida.",
  "“Creo en tu capacidad innata para hacer un excelente trabajo”.",
  "Dale a la gente afectividad y seguridad, y verás cómo su productividad se dispara.",
  "El microlearning 2.0 utiliza la \"traducción pedagógica\" para hacer accesible lo complejo.",
  "“Trabajemos juntos para encontrar una solución verdaderamente innovadora”.",
  "Mantener el cuerpo con buena salud es un deber para mantener la mente despejada.",
  "La asertividad implica ir al punto, eliminando la ambigüedad que genera angustia.",
  "“Comprendo perfectamente por lo que estás pasando en este momento”.",
  "Sin salud, la vida no es vida; es solo un estado de languidez inútil.",
  "El pensamiento histórico dota al profesional de perspectiva ante las crisis cíclicas.",
  "“Quiero que te sientas cómodo/a compartiendo todas tus ideas conmigo”.",
  "Hay heridas invisibles en el alma que duelen mucho más que cualquier fractura.",
  "Las metodologías activas exigen un rol dinámico que previene el aburrimiento y la apatía.",
  "“Juntos podemos alcanzar metas mucho más grandes que de forma individual”.",
  "Sanar es una cuestión de tiempo, pero también de crear el entorno adecuado.",
  "Los plugins de VS Code y asistentes en Slack son los nuevos pupitres del saber.",
  "“Agradezco tu compromiso y tu profunda dedicación a este proyecto”.",
  "Tú eres tan importante para tu salud como tu salud lo es para tu éxito.",
  "La educación socioemocional es la medicina preventiva del siglo XXI.",
  "“Es importante que nos comuniquemos de forma abierta y honesta siempre”.",
  "La salud y la alegría se alimentan mutuamente en un ciclo de bienestar infinito.",
  "El estilo pasivo de comunicación es una renuncia a la propia identidad y poder.",
  "“Trabajemos juntos para encontrar una solución que beneficie a todos los implicados”.",
  "La salud mental no es un destino, sino una práctica diaria de atención y cuidado.",
  "El aprendizaje reflexivo convierte cada error en un ladrillo de la sabiduría futura.",
  "“Confío plenamente en que juntos podemos lograr grandes cosas”.",
  "Cuida de tu cuerpo; es el único vehículo que te llevará hasta tus sueños.",
  "El microlearning invisible es el que sucede sin que el aprendiz sienta que está estudiando.",
  "Mereces tu propio amor y afecto tanto como cualquier otro ser en el universo.",
  "La comunicación asertiva es el antídoto contra la hostilidad del mando tradicional.",
  "Exponer el interior con asertividad es la forma más alta de libertad profesional.",
  "Las simulaciones de roles entrenan el cerebro para la acción sin el peso del riesgo real.",
  "Deja que los alimentos sean tu medicina; la nutrición es el primer paso de la salud.",
  "El mLearning utiliza la gamificación para transformar la rutina en un desafío motivador.",
  "Cuando se pierde la salud, se pierde el motor; cuando se pierde el carácter, se pierde el rumbo.",
  "La asertividad permite decir \"no\" sin romper el puente de la relación interpersonal.",
  "Que no estés enfermo no es garantía de que estés operando en tu máximo potencial de salud.",
  "El trabajo colaborativo a través de la técnica del puzle genera una responsabilidad social real.",
  "Si no cuidas tu cuerpo, no habrá tecnología que pueda suplir tu falta de vitalidad.",
  "El microaprendizaje ofrece claridad en capítulos breves que la mente asimila con placer.",
  "El deseo de controlar la propia vida es una necesidad biológica para la estabilidad mental.",
  "Utilizar frases cortas y directas es un acto de caridad hacia la carga cognitiva ajena.",
  "La salud es la verdadera riqueza; el dinero solo es un facilitador de la misma.",
  "Las metodologías constructivistas valoran el proceso de descubrimiento por encima del resultado.",
  "Demasiadas personas sobrevaloran sus carencias y subestiman sus talentos innatos.",
  "El microaprendizaje digital es la respuesta pedagógica a la falta de tiempo del mundo moderno.",
  "Tener expectativas realistas es la base de un sistema emocional equilibrado y fuerte.",
  "Reemplazar el \"¿entendiste?\" por \"¿me expresé bien?\" traslada la responsabilidad al emisor.",
  "No permitas que lo que no puedes hacer paralice las acciones que sí están bajo tu control.",
  "El aula invertida maximiza el valor del encuentro humano al dejar lo teórico para la soledad.",
  "La primera riqueza es la salud; sin ella, todos los demás activos son irrelevantes.",
  "El microlearning contextual elimina la frustración de buscar información en manuales densos.",
  "Nuestra ansiedad no nace del futuro, sino del intento inútil de controlarlo desde el presente.",
  "Un líder asertivo es un faro de calma en medio de la tormenta organizacional.",
  "El aprendizaje y servicio demuestra que la formación más potente es la que ayuda a otros.",
  "La gamificación narrativa enseña resiliencia al permitir que el error tenga un costo simulado.",
  "La asertividad es el arte de hablar con el corazón pero guiado por la razón clara.",
  "Los módulos psicoeducativos sobre manejo del estrés deberían ser obligatorios en toda formación.",
  "Las intervenciones automáticas en el aprendizaje detectan el fracaso antes de que el alumno abandone.",
  "El microlearning reduce los costos de formación al eliminar el tiempo no productivo de los traslados.",
  "El compañerismo es un factor determinante en la calidad de cualquier proceso educativo.",
  "La salud emocional es la moneda con la que pagamos nuestra capacidad de innovar.",
  "El análisis de casos reales permite que el profesional practique la empatía en situaciones límite.",
  "En 2026, la tecnología EdTech exitosa es la que se vuelve invisible en lo cotidiano.",
  "La comunicación efectiva requiere instrucciones jerarquizadas de lo más a lo menos relevante.",
  "El microlearning es aprendizaje a medida, ajustado a la talla cognitiva de cada usuario.",
  "Las habilidades sociales en las Ciencias Sociales preparan para la ciudadanía activa y crítica.",
  "La autocrítica sana es el motor de la mejora continua; la autocrítica tóxica es el motor de la depresión.",
  "El Aprendizaje Basado en Problemas conecta la academia con el pulso real de la calle.",
  "La salud mental laboral no es un beneficio extra, es una condición de viabilidad empresarial.",
  "El microlearning permite actualizar conocimientos en horas, no en meses.",
  "El pensamiento histórico permite entender que las crisis actuales son oportunidades de evolución.",
  "La interacción directa con expertos es el valor sagrado que la capacitación tradicional debe proteger.",
  "El mLearning es la modalidad reina para el trabajador que aprende en el transporte público.",
  "La flexibilidad cognitiva es la habilidad blanda que garantiza la supervivencia en la IA.",
  "El microlearning incrustado nos enseña que el mundo entero es nuestra aula permanente.",
  "La solidaridad entre colegas es el mejor seguro contra el agotamiento profesional (burnout).",
  "El análisis predictivo permite al sistema educativo ser un apoyo, no solo un calificador.",
  "La comunicación asertiva es la herramienta con la que los líderes construyen seguridad psicológica.",
  "El microlearning ofrece un abanico de posibilidades para personalizar la ruta de cada talento.",
  "La proactividad es la capacidad de actuar antes de que el problema se convierta en una crisis emocional.",
  "Los plugins de VS Code y asistentes de Slack son los nuevos mentores silenciosos de",
  "El compañerismo tiene una relación directa y positiva con la retención del conocimiento.",
  "La gamificación invisible se centra en el compromiso profundo con la resolución de retos.",
  "El pensamiento crítico nos permite discernir entre la información útil y el ruido digital.",
  "Las sesiones de microlearning de 2 a 7 minutos son las más efectivas para la retención.",
  "La asertividad previene los malentendidos que consumen el tiempo y la energía del equipo.",
  "El Aprendizaje Basado en Problemas mejora la cohesión y la responsabilidad compartida.",
  "La salud física es el hardware sobre el que corre el software de nuestra inteligencia.",
  "La educación socioemocional dota al aprendiz de un kit de herramientas para la vida.",
  "El microlearning permite acceder al conocimiento justo en el \"momento de necesidad\".",
  "Las relaciones interpersonales sanas son el mejor lubricante para el engranaje de la productividad.",
  "El análisis de medios es la base de la libertad intelectual en la era de los algoritmos.",
  "La IA educativa ayuda a generar rutas de aprendizaje únicas basadas en errores previos.",
  "La claridad y la simpleza en la comunicación son formas de elegancia y respeto.",
  "El microlearning entrega el conocimiento en dosis que el cerebro puede digerir sin fatiga.",
  "La empatía cultural es esencial para navegar la globalización del trabajo en",
  "El estilo pasivo-agresivo es una fuga de energía que desmotiva a los equipos más brillantes.",
  "La salud mental debe dejar de ser un tabú para convertirse en una prioridad de diseño humano.",
  "El microlearning facilita la democratización del saber en contextos de baja conectividad.",
  "La investigación local incentiva a los estudiantes a abordar problemas de su propia comunidad.",
  "La asertividad es la capacidad de ser transparente sin ser hiriente.",
  "El aprendizaje basado en la comunidad genera un sentido de pertenencia y bienestar social.",
  "El mLearning reduce la ansiedad al eliminar la presión de las aulas masivas.",
  "La autoaceptación es la base sobre la que se construye cualquier cambio de hábito duradero.",
  "Los microcontenidos son la respuesta lógica a la fragmentación de la atención moderna.",
  "Las Ciencias Sociales nos enseñan que la complejidad social es una invitación a la reflexión.",
  "La asertividad es la expresión más alta de la honestidad emocional y el respeto mutuo.",
  "La salud emocional es la mayor riqueza que un líder puede cultivar en su equipo.",
  "El microlearning se adapta orgánicamente a los flujos de las industrias modernas.",
  "El Aprendizaje Basado en Problemas es el puente entre el aula y la excelencia profesional.",
  "La comunicación asertiva es la clave para un relacionamiento humano de alta calidad.",
  "La IA pedagógica debe ser una herramienta de apoyo, nunca un sustituto del calor humano.",
  "El microlearning permite la implementación de programas de formación lúdicos y desafiantes.",
  "La salud física y mental son las dos alas que permiten el vuelo de la creatividad.",
  "El aula invertida transforma al profesor en un mentor y al alumno en un investigador.",
  "El liderazgo asertivo inspira mediante la coherencia entre lo que se dice y lo que se hace.",
  "El microlearning es el formato perfecto para la capacitación técnica constante y rápida.",
  "La empatía y la solidaridad son las competencias que nos hacen humanos en la era de la IA.",
  "La educación en Ciencias Sociales fomenta la mentalidad democrática indispensable para la paz.",
  "La asertividad es la competencia blanda que más rápido mejora el clima de una organización.",
  "El microlearning permite consumir conocimiento de alto rigor en tiempos de transporte.",
  "La salud mental es el prerrequisito para cualquier éxito profesional que sea sostenible.",
  "El aprendizaje reflexivo es el escudo que protege al saber del paso del tiempo.",
  "La asertividad elimina la necesidad de defensas y permite una colaboración auténtica.",
  "El microlearning es una oportunidad de oro para democratizar la formación técnica.",
  "La salud física es el cimiento de una vida profesional vibrante y llena de propósito.",
  "El aprendizaje contemporáneo es un acto de amor hacia uno mismo y un respeto al mundo.",
];
